In [7]:
from bs4 import BeautifulSoup
import pandas as pd
import requests
url="https://www.basketball-reference.com/leagues/NBA_2020_totals.html"
req=requests.get(url)
soup=BeautifulSoup(req.content,"html.parser")
table=soup.find(name="table")
df=pd.read_html(str(table))[0].set_index("Rk")
df.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
Rk,,,,,,,,,,,,,,,,,,,,,
1,Steven Adams,C,26,OKC,63,63,1680,283,478,.592,...,.582,207,376,583,146,51,67,94,122,684
2,Bam Adebayo,PF,22,MIA,72,72,2417,440,790,.557,...,.691,176,559,735,368,82,93,204,182,1146
3,LaMarcus Aldridge,C,34,SAS,53,53,1754,391,793,.493,...,.827,103,289,392,129,36,87,74,128,1001
4,Kyle Alexander,C,23,MIA,2,0,13,1,2,.500,...,NaN,2,1,3,0,0,0,1,1,2
5,Nickeil Alexander-Walker,SG,21,NOP,47,1,591,98,266,.368,...,.676,9,75,84,89,17,8,54,57,267